import os

import psycopg
from psycopg.rows import dict_row


DATABASE_URL = os.getenv("DATABASE_URL")


def get_connection():
    if not DATABASE_URL:
        raise SystemExit("DATABASE_URL is not set.")
    return psycopg.connect(DATABASE_URL, row_factory=dict_row)


def ensure_identity(conn, table_name):
    with conn.cursor() as cur:
        cur.execute(
            "SELECT is_identity FROM information_schema.columns "
            "WHERE table_name = %s AND column_name = 'id'",
            (table_name,),
        )
        row = cur.fetchone()
        if not row:
            return
        is_identity = row["is_identity"]
        if is_identity != "YES":
            cur.execute(
                f"ALTER TABLE {table_name} ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY"
            )


def ensure_identities(conn, table_names):
    for table_name in table_names:
        ensure_identity(conn, table_name)


def set_audit_user_id(conn, user_id):
    with conn.cursor() as cur:
        cur.execute("SELECT set_config('app.user_id', %s, true)", (str(user_id),))
