import os

from db import get_connection


def main():
    if not os.getenv("DATABASE_URL"):
        raise SystemExit("DATABASE_URL is not set.")

    with get_connection() as conn:
        cursor = conn.cursor()
        cursor.execute(
            """
            CREATE TABLE IF NOT EXISTS active_sessions (
                id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                session_key TEXT NOT NULL UNIQUE,
                user_id INTEGER REFERENCES user_accounts(id),
                last_seen_at TIMESTAMP NOT NULL,
                user_agent TEXT,
                ip_address TEXT
            )
            """
        )
        cursor.execute(
            """
            CREATE INDEX IF NOT EXISTS idx_active_sessions_last_seen
                ON active_sessions(last_seen_at)
            """
        )
        conn.commit()

    print("active_sessions table migration complete.")


if __name__ == "__main__":
    main()
